# Generated by Django 5.0.7 on 2024-11-28 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Electrodomestico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del electrodoméstico', max_length=100)),
                ('watts', models.FloatField(help_text='Consumo en watts')),
                ('horas_uso', models.FloatField(help_text='Horas de uso por día')),
                ('dias_uso', models.IntegerField(help_text='Días de uso por semana')),
            ],
        ),
    ]
