# Generated by Django 5.1.3 on 2024-11-28 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_baterias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='cantidad',
            field=models.IntegerField(default=1, help_text='Cantidad de electrodomésticos'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='dias_uso',
            field=models.IntegerField(default=7, help_text='Días de uso por semana'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='horas_uso',
            field=models.FloatField(default=1.0, help_text='Horas de uso por día'),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='nombre',
            field=models.CharField(default='Electrodoméstico Genérico', help_text='Nombre del electrodoméstico', max_length=100),
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='watts',
            field=models.FloatField(default=100.0, help_text='Consumo en watts'),
        ),
    ]
