# Generated by Django 5.1.3 on 2024-11-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_baterias', '0002_electrodomestico_cantidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electrodomestico',
            name='alimentacion',
            field=models.CharField(choices=[('AC', 'Corriente Alterna'), ('DC', 'Corriente Directa')], default='AC', help_text='Tipo de alimentación (AC o DC)', max_length=2),
        ),
    ]
