# Generated by Django 5.1.3 on 2024-11-28 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_baterias', '0003_electrodomestico_alimentacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calculos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tension_sistema', models.FloatField(default=120.0, help_text='Voltaje del sistema (VAC)')),
                ('dias_autonomia', models.IntegerField(default=3, help_text='Días de autonomía')),
                ('porcentaje_descarga', models.FloatField(default=60.0, help_text='% de descarga')),
                ('sistema_dc', models.FloatField(default=48.0, help_text='Sistema en voltios DC')),
                ('capacidad_bateria', models.FloatField(default=250.0, help_text='Capacidad de baterías (mAh)')),
                ('eficiencia_sistema', models.FloatField(default=85.0, help_text='Eficiencia del sistema (%)')),
                ('potencia_modulo', models.FloatField(default=300.0, help_text='Potencia de módulos (W)')),
                ('voltaje_modulo', models.FloatField(default=12.0, help_text='Voltaje de módulos (V)')),
                ('corriente_nominal', models.FloatField(default=4.0, help_text='Corriente nominal de módulos (A)')),
                ('corriente_corta_circuito', models.FloatField(default=4.5, help_text='Corriente de corto circuito (A)')),
                ('potencia_inversor', models.FloatField(default=4000.0, help_text='Potencia del inversor (W)')),
                ('eficiencia_inversor', models.FloatField(default=92.0, help_text='Eficiencia del inversor (%)')),
                ('horas_sol_dia', models.FloatField(default=6.0, help_text='Horas de sol pico por día')),
            ],
        ),
        migrations.AlterField(
            model_name='electrodomestico',
            name='nombre',
            field=models.CharField(help_text='Nombre del electrodoméstico', max_length=100),
        ),
    ]
