# Generated by Django 5.1.3 on 2024-11-28 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculo_baterias', '0004_calculos_alter_electrodomestico_nombre'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calculos',
            new_name='Configuracion',
        ),
    ]
